config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'events#index'
  get 'help' => 'static_pages#help', as: :help
  get 'about' => 'static_pages#about', as: :about
  post 'invitations/:id' => 'invitations#create', as: :invitations
  resources :users,    		only: [:new, :create, :show]
  resources :sessions, 		only: [:new, :create, :destroy]
  resources :events,   		only: [:new, :create, :show, :index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :creator, class_name: "User"
	has_many :invitations, foreign_key: "attended_event_id"
	has_many :attendees, through: :invitations

	validates :name, :location, :description, :date, presence: true

	scope :future, -> { where("date > ?", Time.zone.now) }
	scope :past,   -> { where("date < ?", Time.zone.now) }
	
end

app/models/invitation.rb
class Invitation < ApplicationRecord
	belongs_to :attended_event, class_name: "Event"
	belongs_to :attendee, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
	has_many :events, foreign_key: :creator_id
	has_many :invitations, foreign_key: :attendee_id
	has_many :attended_events, through: :invitations

	def future_events
		self.attended_events.where("date > ?", Time.zone.now).all
	end

	def past_events
		self.attended_events.where("date < ?", Time.zone.now).all
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
  protect_from_forgery with: :exception

  def current_page
  	request.referrer
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def new
		@event = Event.new
	end

	def create
		user = User.find session[:user_id]
		@event = user.events.build event_params
		if @event.save
			redirect_to user_path(user)
		else
			render :new
		end
	end

	def show
		@event = Event.find params[:id]
		@attendees = @event.attendees.all
	end

	def index
		@events_future = Event.future.all
		@events_past = Event.past.all
	end

	private

		def event_params
			params.require(:event).permit(:date, :location, :name, :description)
		end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def create
  	event = Event.find(params[:id])
  	invitation = Invitation.new(attendee: current_user, attended_event: event)
  	invitation.save
  	redirect_to current_page
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by_name(params[:session][:id]) || \
					 User.find_by_id(params[:session][:id])
		if user
			log_in user
			redirect_to user_url(user)
		else
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new user_params
		if @user.save
			log_in @user
			redirect_to user_url(@user)
		else
			render :new
		end
	end

	def show
		@user = User.find params[:id]
		@events = @user.events.all
		@attended_events_past = @user.past_events
		@attended_events_future = @user.future_events
	end

	private

		def user_params
			params.require(:user).permit(:name)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the current user is logged in and false if not
  def logged_in?
  	!current_user.nil?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<% if !logged_in? %>
	<div class="center">
		<%= link_to "Sign Up!", new_user_path, class: "btn btn-primary" %>
	</div>
<% else %>	
	<div class="center">
		<%= link_to "Plan an event!", new_event_path, class: "btn btn-primary" %>
	</div>
	<h2>Upcoming Events</h2>
	<%= render partial: 'shared/titles' if @events_future.any? %>
	<div class="panel-group" id="accordion1">
		<% @events_future.each do |event| %>
			<%= render partial: 'shared/accordion', locals: { event: event, parent: 'accordion1' } %>
		<% end %>
	</div>

	<h2>Past Events</h2>
	<%= render partial: 'shared/titles' if @events_past.any?%>
	<div class="panel-group" id="accordion2">
		<% @events_past.each do |event| %>
			<%= render partial: 'shared/accordion', locals: { event: event, parent: 'accordion2' } %>
		<% end %>
	</div>
<% end %>

app/views/events/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">		
		<%= form_for @event do |f| %>
			<%= f.label :title %>
			<%= f.text_field :name, class: 'form-control' %>
			<%= f.label :location %>
			<%= f.text_field :location, class: 'form-control' %>
			<%= f.label :description %>
			<%= f.text_field :description, class: 'form-control' %>
			<%= f.label :date %>
      <%= f.datetime_field :date, class: 'form-control date-field' %><br>
			<%= f.submit "Create", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>
<p>When: <%= @event.date.strftime("%b %d, %Y | %l:%M %p") %></p>
<p>Where: <%= @event.location %></p>
<p>Description: <%= @event.description %></p>
<p>Creator: <%= @event.creator.name %></p>

<%= link_to "Attend this event", '#', class: "btn btn-success" unless @attendees.include? current_user%>

<% if @attendees.count != 0 %>
	<h2>Who is going</h2>
	<% @attendees.each do |attendant| %>
		<p><%= attendant.name %></p>
	<% end %>
<% else %>
	<h2>No one is attending this event...</h2>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.theodinproject.com/">Odin Project</a>
    | <a href="http://www.theodinproject.com/ruby-on-rails/associations">Active Record Associations</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Private Events", root_path, id: "logo" %>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
        data-target=".navbar-collapse">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
    		</button>
    	</div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Events", root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to current_user.name, '#', class: "profile-name" %>
              <li class="divider"></li>
              <li><%= link_to "Profile", user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", session_path(current_user), method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", new_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <script   src="https://code.jquery.com/jquery-3.0.0.min.js"   integrity="sha256-JmvOoLtYsmqlsWxa7mDSLMwa6dZ9rrIdtrrVYRnDRH0="   crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  </head>

  <body>
  	<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_accordion.html.erb
<div class="row">
	<div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <div data-toggle="collapse" data-parent="#<%=parent%>" href="#<%=parent%><%=event.id%>" data-target="#<%=parent%><%=event.id%>">
        	<div class="name heading col-xs-3">
        		<p><%=event.name%></p>
        	</div>
        	<div class="date heading col-xs-3">
        		<p><%=event.date.strftime("%b %d, %Y | %l:%M %p")%></p>
        	</div>
        	<div class="location heading col-xs-3">
        		<p><%=event.location%></p>
        	</div>
        	<div class="creator heading col-xs-3">
        		<p><%=event.creator.name %></p>
        	</div>
        </div>
      </h4>
    </div>
    <div id="<%=parent%><%=event.id%>" class="panel-collapse collapse">
      <div class="panel-body">
      	<div class="row">
      		<div class="col-md-8 col-sm-7 col-xs-6 about">
      			<%=event.description%>
      		</div>
      		<div class="col-md-4 col-sm-5 col-xs-6">
      			<%=
              link_to "Attendance List", event_path(event), class: "btn btn-primary"
            %>
            <%= link_to "Attend this event", invitations_path(event.id), method: :post, class: "btn btn-success" unless event.attendees.include? current_user%>
      		</div>
      	</div>
      </div>
    </div>
	</div>
</div>

app/views/shared/_titles.html.erb
<div class="row titles-bar">
  <div class="center col-xs-3">
    <p>Name</p>
  </div>
  <div class="center col-xs-3">
    <p>When</p>
  </div>
  <div class="center col-xs-3">
    <p>Where</p>
  </div>
  <div class="center col-xs-3">
    <p>Creator</p>
  </div>
</div>

app/views/static_pages/about.html.erb
<h1>Project outline and instructions.</h1>

<h2>Project 2: Private Events</h2>

<p>
	You want to build a site similar to a private Eventbrite which allows users to create events and then manage user signups. Users can create events and send invitations and parties (sound familiar?). Events take place at a specific date and at a location (which you can just store as a string, like "Andy's House").
<p>
<br>
<p>
	A user can create events. A user can attend many events. An event can be attended by many users. This will require you to model many-to-many relationships and also to be very conscious about your foreign keys and class names (hint: you won't be able to just rely on Rails' defaults like you have before).
</p>

<h2>Your Task</h2>
<p>
	We've gotten quite far here, so these tasks will only lay out the high level overview of what you're meant to build. You'll need to implement the details yourself. As usual, it's not meant to look pretty, just work. Design is all extra credit.
</p>

<h2>Setup and Sign In</h2>

<p>1. Model the data for your application, including the necessary tables.</p>
<p>2. Create a new Rails application and Git repo called private-events.</p>
<p>3. Update your README to be descriptive and link to this project.</p>
<p>4. Build and migrate your User model. Don't worry about validations.</p>
<p>
	5. Create a simple Users controller and corresponding routes for #new, #create, and #show actions. You'll need to make a form where you can sign up a new user and a simple #show page. You should be getting better and faster at this type of vanilla controller/form/view building.
</p>
<p>
	6. Create a simple sign in function that doesn't require a password -- just enter the ID or name of the user you'd like to "sign in" as and click Okay. You can then save the ID of the "signed in" user in either the session hash or the cookies hash and retrieve it when necessary. It may be helpful to always display the name of the "signed in" user at the top.
</p>
<br>
<h2>Basic Events</h2>

<p>
	1. Build and migrate your Event model without any foreign keys. Don't worry about validations. Include the event's date in your model but don't worry about doing anything special with it yet.
</p>
<p>
	2. Add the association between the event creator (a User) and the event. Call this user the "creator". Add the foreign key to the Events model as necessary. You'll need to specify your association properties carefully (e.g. :foreign_key, :class_name, and :source).
</p>
<p>
	3. Modify your User's Show page to list all the events a user has created.
</p>
<p>
	4. Create an EventsController and corresponding routes to allow you to create an event (don't worry about editing or deleting events), show a single event, and list all events.
</p>
<p>
	5. The form for creating an event should just contain a :description field.
</p>
<p>
	6. The #create action should use the #build method of the association to create the new event with the user's ID prepopulated. You could easily also just use Event's ::new method and manually enter the ID but... don't.
</p>
<p>
	7. The event's Show page should just display the creator of the event for now.
</p>
<p>
	8. Create the Event Index page to display all events.
</p>
<h2>Event Attendance</h2>

<p>
	1. Now add the association between the event attendee (also a User) and the event. Call this user the "attendee". Call the event the "attended_event". You'll again need to juggle specially named foreign keys and classes and sources.
</p>
<p>
	2. Create and migrate all necessary tables and foreign keys. This will require a "through" table since an Event can have many Attendees and a single User (Attendee) can attend many Events... many-to-many.
</p>
<p>
	3. Now make an Event's Show page display a list of attendees.
</p>
<p>
	4. Make a User's Show page display a list of events he is attending.
</p>
<p>
	5. Modify the User's Show page to separate those events which have occurred in the past ("Previously attended events") from those which are occuring in the future ("Upcoming events"). You could do this by putting logic in your view. Don't. Have your controller call separate model methods to retrieve each, e.g. @upcoming_events = current_user.upcoming_events and @prev_events = current_user.previous_events. You'll get some practice with working with dates as well as building some queries.
</p>
<p>
	6. Modify the Event Index page to list all events, separated into Past and Upcoming categories. Use a class method on Event (e.g. Event.past).
</p>
<p>
	7. Refactor the "upcoming" and "past" methods into simple scopes (remember scopes??).
</p>
<p>
	8. Put navigation links across the top to help you jump around.
</p>
<p>
	9. Extra Credit: Allow users to invite other users to events. Only allow invited users to attend an event.
</p>
<p>
	10. Push to Github.
</p>

app/views/static_pages/help.html.erb
<h1>Make events and rsvp to events.</h1>
<h2>Make an account</h2>
<p>To make an account, simply visit the events page when not logged in, and click sign up. Enter a name, and your account will be created and you will be logged in automatically.</p>
<p>Remember the name, because you will use it to sign back in later.</p>

<h2>Making Events</h2>
<p>To make an event, go to the events page and click "Place an event!" This will take you to an event creation form. All fields are required and the form will not submit until they have all been filled out.</p>

<h2>RSVP'ing</h2>
<p>To attend an event, simply go to the events page and click on an event. This will expand the event, showing the description and some buttons. Click on "Attent this event". You will be added to the attending list. Similarly, you can view who is attending the event by clicking "Attendance list"</p>

<h2>Your events</h2>
<p>To view your events click on the account dropdown button and then select profile. This will bring you to your profile page where you can see all of the events you have created, as well as events you have or will be attending.</p>

app/views/users/new.html.erb
<div class="row">	
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @user do |f| %>

			<%= f.label :name %>
			<%= f.text_field :name %>
			<%= f.submit "Signup", class: "btn btn-primary" %>

		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<h2>Hosted Events</h2>
<%= render partial: 'shared/titles' if @events.any? %>
<div class="panel-group" id="accordion1">
	<% @events.each do |event| %>
		<%= render partial: 'shared/accordion', locals: { event: event, parent: 'accordion1' } %>
	<% end %>
</div>

<h2>Upcoming Events</h2>
<%= render partial: 'shared/titles' if @attended_events_future.any? %>
<div class="panel-group" id="accordion2">
	<% @attended_events_future.each do |event| %>
		<%= render partial: 'shared/accordion', locals: { event: event, parent: 'accordion2' } %>
	<% end %>
</div>

<h2> Previously attended Events</h2>
<%= render partial: 'shared/titles' if @attended_events_past.any? %>
<div class="panel-group" id="accordion3">
	<% @attended_events_past.each do |event| %>
		<%= render partial: 'shared/accordion', locals: { event: event, parent: 'accordion3' } %>
	<% end %>
</div>